# Generated by Django 2.1.1 on 2018-12-10 15:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='نام کاربری')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('marketer', models.BooleanField(default=False, verbose_name='بازاریاب')),
                ('used_free', models.BooleanField(default=False, verbose_name='از مدت رایگان استفاده کرده')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='کد تایید')),
                ('participation', models.IntegerField(default=0, verbose_name='سود مشارکت')),
                ('income', models.IntegerField(default=0, verbose_name='درآمد')),
                ('activation_key', models.CharField(default='0', max_length=40, verbose_name='کد فعالسازی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='معرف')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام فعالیت')),
                ('detail', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات فعالیت')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='زمان فعالیت')),
                ('cid', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=False, verbose_name='مبلغ')),
                ('done', models.BooleanField(default=False, verbose_name='انجام شده')),
                ('items', django_mysql.models.JSONField(default=dict, verbose_name='اقلام')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='زمان خرید')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='نام پلن')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('time', models.CharField(default='', max_length=512, verbose_name='مدت زمان پلن')),
                ('followers1', models.IntegerField(default=0, verbose_name='حداقل تعداد افزایش فالوور')),
                ('followers2', models.IntegerField(default=0, verbose_name='حداکثر تعداد افزایش فالوور')),
                ('charge', models.IntegerField(verbose_name='میزان شارژ')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Plan', verbose_name='پلن'),
        ),
    ]
