# Generated by Django 2.1.1 on 2018-12-10 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='تصویر')),
                ('text', models.CharField(max_length=1024, verbose_name='متن')),
                ('type', models.IntegerField(verbose_name='نوع')),
                ('seen', models.BooleanField(default=False, verbose_name='دیده شده')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
        ),
    ]
