# Generated by Django 2.1.1 on 2018-12-10 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='موضوع تیکت')),
                ('text', models.CharField(max_length=1024, verbose_name='متن تیکت')),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='', verbose_name='پیوست')),
                ('reply', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='پاسخ')),
                ('seen', models.BooleanField(default=False, verbose_name='دیده شده')),
                ('replied', models.BooleanField(default=False, verbose_name='پاسخ داده شده')),
                ('sent_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ارسال')),
                ('replied_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ارسال پاسخ')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
        ),
    ]
